context:
  version: 0.1.7.post5
#  lib_ver: ${{ (version | split("."))[:3] | join(".") }}
  lib_ver: 0.1.8

package:
  name: qdldl-python
  version: ${{ version }}

source:
  url: https://github.com/osqp/qdldl-python/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 498002a3826dca9d03186972ca82ee8acb930127ea5603b94a845327ffa98a7c
  patches:
    - patches/0001-use-Ninja-everywhere.patch
    - patches/0002-build-against-conda-forge-s-libqdldl.patch
    - patches/0003-build-qdldlamd-as-shared-lib-and-install-it.patch
    - patches/0004-Do-not-pass-CMAKE_GENERATOR-as-variable.patch

build:
  number: 2
  script:
    - python -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - setuptools
    - libqdldl =${{ lib_ver }}
    - numpy
    - pybind11
  run:
    - python
    - scipy

tests:
  - python:
      imports:
        - qdldl
  - requirements:
      run:
        - pytest
    files:
      source:
        - tests/
    script:
      # Disabled tests due to issues in QEMU, see https://github.com/scipy/scipy/issues/14560
      - if: not ppc64le
        then: pytest tests
        else: echo skipped

about:
  homepage: https://github.com/oxfordcontrol/qdldl-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Python interface to the QDLDL free LDL factorization routine for quasi-definite linear systems

  description: |
    Python interface to the [QDLDL](https://github.com/oxfordcontrol/qdldl/) free
    LDL factorization routine for quasi-definite linear systems: `Ax = b`.
  repository: https://github.com/oxfordcontrol/qdldl-python

extra:
  recipe-maintainers:
    - adament
    - bstellato
    - gbanjac
    - h-vetinari
